# Uncomment the next line to define a global platform for your project
# platform :ios, '15.4'

target 'GOYO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GOYO
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Firestore'
  pod 'Alamofire'
  pod 'SwiftyJSON'

end
