# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheongBit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheongBit

	pod 'DLRadioButton', '~> 1.4'

end
